name: buscatelo
description: Hotel finding. An awesome Flutter challenge.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.5.0
  provider: ^6.0.0
  lottie: ^2.7.0
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  google_fonts: ^6.1.0
  flutter_staggered_animations: ^1.1.1
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  pedantic: ^1.8.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/img/logo.png"
  image_path_android: "assets/img/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/images/
